### PR TITLE
OAuth 2.0 Refresh Token grant Flow

### PR DESCRIPTION
**Pull request by omar25h**
added OAuth 2.0 refresh_token grant flow

### CODE REVIEW

**Comment by Rainer-Lang** [comment]
Any news?

**Comment by amitshekhariitbhu** [comment]
@Rainer-Lang I will check it and merge it soon.

**Comment by Rainer-Lang** [comment]
@amitshekhariitbhu Thanks.
Little suggestion: Make a small sample.

**Comment by xdnan7** [comment]
@amitshekhariitbhu Any update about this ?

**Comment by amitshekhariitbhu** [comment]
Not required by many developers. So, closing as of now.

**Pull request closed without merging**
