### PR TITLE
Added support for displaying the upload progress of POST, PUT and PAT…

### PR DESCRIPTION
**Pull request by dg76**
Hi!

I have added support for displaying the upload progress of POST, PUT and PATCH commands and tested it with a POST request, which seems to work fine. What do you think? Would you like to integrate this? Is it good/usable this way? 🤔

Kind regards

Dominique

### CODE REVIEW

**Comment by amitshekhariitbhu** [comment]
Let me test this once

**Comment by dg76** [comment]
Hi! Did you make any progress?

**Comment by amitshekhariitbhu** [comment]
@dg76 Please make PR in development branch.

**Comment by dg76** [comment]
Ok, I have changed the branch. Why didn't you change it yourself?

**Comment by dg76** [comment]
Will you reopen this pull request or should I create e.g. an Issue for it?

**Pull request merged**
